apps/members/urls.py
from django.urls import path
from .views import *

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    
    path('profile/update/', profile_update_view, name='profile_update'),
    path('password/change/', password_change_view, name='change_password'),
    
    path('profile/<str:username>', profile_view, name='profile'),
    path('profile/<str:username>/follow/', follow_view, name='follow'),
    path('profile/<str:username>/privacy/', privacy_view, name='privacy'),
    
    path('search/', search_view, name='search_profile'),
    
    ] 

apps/order/urls.py
from django.urls import path

from .views import (AddToCartView, CartView, DeleteFromCartView, 
                    ClearCartView, CartOrderingView, OrderComplete, CartUpdateView)

app_name = 'order'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', AddToCartView.as_view(), name='add_to_cart'),
    
    path('cart/remove/<int:pk>/', DeleteFromCartView.as_view(), name='cart_remove'),
    path('cart/clear/', ClearCartView.as_view(), name='cart_clear'),

    path('cart/update/<int:cart_id>/<str:action>/', CartUpdateView.as_view(), name='cart_item_update'), 

    path('cart/ordering', CartOrderingView.as_view(), name='cart_ordering'),

    path("complete/<int:order_id>/", OrderComplete.as_view(), name='complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    path('blog/', include('apps.blog.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('order/', include('apps.order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Кількість')
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity} шт.'
    
    class Meta:
        verbose_name = 'Кошик'
        verbose_name_plural = 'Кошики'
        ordering = ('id',)
        # unique_together = ('user', 'product' ) # Щоб не можна було додати один і той же товар в корзину більше одного разу
    
    def total_price(self):
        return self.product.price * self.quantity
        
#ДОробити модель обраного товару та відображення обраного товару в адмінці
class Favorite(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    
    def __str__(self):
        return f'{self.product.name}'
    
    class Meta:
        verbose_name = 'Обране'
        verbose_name_plural = 'Обране'
        unique_together = ('user', 'product' ) # Щоб не можна було додати один і той же товар в обране більше одного разу
        
        
class Order(models.Model):
    STATUS_CHOICES = (
        ('in_progress', 'В обробці'),
        ('sent', 'Відправлено'),
        ('completed', 'Завершено'),
        ('canceled', 'Скасовано')
    )
    STATUS_PAID = (
        (True, 'Оплачено'),
        (False, 'Не оплачено')
    )
    
    
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Загальна вартість')
    
    first_name = models.CharField(max_length=255, verbose_name='Ім\'я')
    last_name = models.CharField(max_length=255, verbose_name='Прізвище')
    email = models.EmailField(verbose_name='Email', blank=True, null=True)
    phone = PhoneNumberField(verbose_name='Телефон')
    address = models.CharField(max_length=255, verbose_name='Адреса')
    comment = models.TextField(verbose_name='Коментар', blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')

    paid = models.BooleanField(verbose_name='Оплачено', choices=STATUS_PAID, default=False)
    status = models.CharField(max_length=255, verbose_name='Статус', choices=STATUS_CHOICES, default='in_progress')

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'
        ordering = ('-created_at',)
        
    def __str__(self):
        return f'Замовлення №{self.id}'
    
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Кількість')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity} шт.'
    
    class Meta:
        verbose_name = 'Товар замовлення'
        verbose_name_plural = 'Товари замовлення'
        
    def total_price(self):
        return self.product.price * self.quantity

apps/order/forms.py
from django import forms

from .models import Cart, Order



class CartAddProductForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ('user', 'product', 'quantity')
        widgets = {
            'user': forms.HiddenInput(), # Поле user приймає значення з запиту, тому його не потрібно відображати на формі
            'product': forms.HiddenInput(),
            'quantity': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'max': 100, 'value': 1})
        }
        
    def clean(self):
        cleaned_data = super().clean()
        product = cleaned_data.get('product')
        quantity = cleaned_data.get('quantity')
        
        if product.quantity < quantity:
            raise forms.ValidationError('На складі недостатньо товару')

        return cleaned_data

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'phone', 'address', 'comment')


class CartUpdateForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ('quantity',)
        widgets = {
            'quantity': forms.NumberInput(attrs={'class': 'form-control'})
        }

    def clean(self):
        cleaned_data = super().clean()
        product = self.instance.product
        quantity = cleaned_data.get('quantity')

        if product.quantity < quantity:
            raise forms.ValidationError('На складі недостатньо товару')
        elif quantity < 1:
            raise forms.ValidationError('Кількість товару не може бути менше 1')

        return cleaned_data

apps/order/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import transaction

from apps.main.mixins import ListViewBreadcrumbMixin
from .forms import CartAddProductForm, OrderCreateForm, CartUpdateForm
from .models import Cart, OrderProduct, Order

# Create your views here.
def get_cart_data(user_id):
    cart = Cart.objects.filter(user=user_id).prefetch_related('product').prefetch_related('product__images')
    total_price = sum([item.total_price() for item in cart])
    return {'cart': cart, 'total_price': total_price}


class CartView(LoginRequiredMixin, ListViewBreadcrumbMixin):
    model = Cart
    template_name = 'order/cart.html'
    context_object_name = 'cart'
    
    def get_queryset(self):
        return Cart.objects.filter(user=self.request.user).prefetch_related('product').prefetch_related('product__images')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_price'] = sum([item.total_price() for item in self.get_queryset()])
        return context
    
    def get_breradcrumb(self):
        self.breadcrumbs = {
            'current': 'Кошик',
        }
        return self.breadcrumbs
    
class AddToCartView(LoginRequiredMixin, View):
    def get(self, request):
        data = request.GET.copy() # Копіюємо дані з запиту
        data.update(user=request.user)
        request.GET = data
        
        form = CartAddProductForm(request.GET)
        
        if form.is_valid():
            cart = form.save(commit=False)
            product_in_cart = Cart.objects.filter(user=request.user, product=cart.product).first()
            if product_in_cart:
                product_in_cart.quantity = cart.quantity
                product_in_cart.save()
                messages.success(request, f'Кількість товару {cart.product.name} змінено на {cart.quantity}')

            else:
                cart.save()
                messages.success(request, f'Товар {cart.product.name} додано в корзину')
            return redirect('catalog:product', slug=cart.product.slug, category_slug=cart.product.main_category().slug)
        else:
            messages.error(request, 'Помилка додавання товару в корзину')
            return redirect('catalog:index')
        
        
class DeleteFromCartView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = kwargs.get('pk')
        cart = get_object_or_404(Cart, pk=cart_id)
        cart.delete()
        messages.success(request, f'Товар {cart.product.name} видалено з корзини')
        return redirect('order:cart')
    
class ClearCartView(LoginRequiredMixin, View):
    def get(self, request):
        Cart.objects.filter(user=request.user).delete()
        messages.success(request, 'Корзина очищена')
        return redirect('order:cart')
    
    
class CartOrderingView(CartView):
    template_name = 'order/cart_ordering.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OrderCreateForm()
        return context

    def get_breradcrumb(self):
        self.breadcrumbs = {
            f'{reverse("order:cart")}': 'Кошик',
            'current': 'Оформлення замовлення',
        }   
        return self.breadcrumbs

    def post(self, request):
        form = OrderCreateForm(request.POST)
        cart_data = get_cart_data(request.user.id)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.total_price = cart_data.get('total_price')
            order.save()

            #очищаємо корзину і добавляємо товари в замовлення в одній транзакції
            with transaction.atomic():
                for item in cart_data.get('cart'):
                    order_product = OrderProduct(
                        order=order, 
                        product=item.product, 
                        quantity=item.quantity, 
                        price=item.product.price)
                    order_product.save()
                    item.product.quantity -= item.quantity # зменшуємо кількість товару на складі
                    item.product.save() # зберігаємо зміни
                Cart.objects.filter(user=request.user).delete()

            messages.success(request, 'Замовлення успішно оформлено')
            return redirect('order:complete', order_id=order.id)
        else:
            messages.error(request, f'Помилка оформлення замовлення: {form.errors}')
            return redirect('order:cart_ordering')

class OrderComplete(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):

        order_id = kwargs.get('order_id')

        context = {
            'order': Order.objects.get(pk=order_id)
        } 
        return render(request, 'order/order_complete.html', context=context)

    def post(self, request):
        return redirect('order:cart')
    


class CartUpdateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        cart_id = kwargs.get('cart_id')
        action = kwargs.get('action')
        cart = get_object_or_404(Cart, pk=cart_id)
        if action == 'add':
            cart.quantity += 1
            cart.save()
        elif action == 'remove':
            cart.quantity -= 1
            if cart.quantity == 0:
                cart.quantity = 1
                messages.error(request, f'Кількість товару {cart.product.name} не може бути менше 1')
            cart.save()

        if cart.quantity > cart.product.quantity:
                messages.add_message(request, messages.ERROR, f'На складі недостатньо товару {cart.product.name}', extra_tags='danger')
                cart.quantity = cart.product.quantity
                cart.save()
                return redirect('order:cart')
        messages.success(request, f'Кількість товару {cart.product.name} змінено на {cart.quantity}')


        return redirect('order:cart')

    def post(self, request, *args, **kwargs):
        cart_id = kwargs.get('cart_id')
        cart = get_object_or_404(Cart, pk=cart_id)

        form = CartUpdateForm(request.POST, instance=cart)

        if form.is_valid():
            quantity = form.cleaned_data.get('quantity')
            cart.quantity = quantity
            cart.save()
            messages.success(request, f'Кількість товару {cart.product.name} змінено на {quantity}')
        else:
            messages.error(request, f'Помилка зміни кількості товару: {[error for error in form.errors.values()][0][0]}', extra_tags='danger')

        return redirect('order:cart')

apps/order/templates/order/cart.html
{% extends 'base.html' %}
{% block title %}Каталог{% endblock %}
{% block content %}
   <!-- Таблиця карзина -->
    <div class="container mt-3">
     <h3>Корзина</h3>
     <table class="table">
          <thead>
                <tr>
                 <th scope="col">№</th>
                 <th scope="col">Назва</th>
                 <th scope="col">Зображення</th>
                 <th scope="col">Ціна</th>
                 <th scope="col">Кількість</th>
                 <th scope="col">Сума</th>
                 <th scope="col">Дія</th>
                </tr>
          </thead>
          <tbody>
                {% for item in cart %}
                <tr>
                 <th scope="row">{{ forloop.counter }}</th>
                 <td><a href="{{item.product.get_absolute_url}}">{{ item.product.name }}</a></td>
                 <td>
                    <a href="{{item.product.get_absolute_url}}">
                        <img src="{{ item.product.main_image.image_thumbnail.url }}" alt="{{ item.product.name }}" width="50">
                    </a>
                </td>
                 <td>{{ item.product.price }}</td>
                 <td class="d-flex align-items-center">
                   <a href="{% url 'order:cart_item_update' cart_id=item.id   action='add' %}" class="btn btn-primary btn-sm">+</a>
                    <form method="post" class="mx-2" action="{% url 'order:cart_item_update' cart_id=item.id  action='update' %}">
                      {% csrf_token %}
                      <input type="number" name="quantity" value="{{ item.quantity }}" class="form-control" style="width: 100px;" onchange="this.form.submit()">
                    </form>
                    <a href="{% url 'order:cart_item_update' cart_id=item.id   action='remove' %}" class="btn btn-primary btn-sm">-</a>
               </td>
                 <td>{{ item.total_price }}</td>
                 <td>
                      <a href="{% url 'order:cart_remove' item.id %}" class="btn btn-danger btn-sm">Видалити</a>
                 </td>
                </tr>
                {% endfor %}
                <tr>
                 <td colspan="4">Всього</td>
                 <td>{{ total_price }}</td>
                 <td>
                      <a href="{% url 'order:cart_clear' %}" class="btn btn-danger btn-sm">Очистити</a>
                 </td>
                </tr>
          </tbody>
     </table>
     <a href="{% url 'order:cart_ordering' %}" class="btn btn-success">Оформити замовлення</a>
    </div>
{% endblock %}

apps/order/templates/order/cart_ordering.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Таблиця карзина -->
<div class="container mt-3">
    <div class="row">
        <div class="col-6">
            <h3>Корзина</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Назва</th>
                        <th scope="col">Зображення</th>
                        <th scope="col">Ціна</th>
                        <th scope="col">Кількість</th>
                        <th scope="col">Сума</th>
                        
                        <th scope="col">Дія</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{{item.product.get_absolute_url}}">{{ item.product.name }}</a></td>
                        <td>
                            <a href="{{item.product.get_absolute_url}}">
                                <img src="{{ item.product.main_image.image_thumbnail.url }}" alt="{{ item.product.name }}" width="50">
                            </a>
                        </td>
                        <td>{{ item.product.price }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total_price }}</td>
                        
                        <td>
                            <a href="{% url 'order:cart_remove' item.id %}" class="btn btn-danger btn-sm">Видалити</a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="5">Всього</td>
                        <td>{{ total_price }}</td>
                        <td>
                            <a href="{% url 'order:cart_clear' %}" class="btn btn-danger btn-sm">Очистити</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form | crispy }}

                <button type="submit" class="btn btn-primary">Замовити</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

apps/order/templates/order/order_complete.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}



{% block content %}

   <!-- Таблиця карзина -->
    <div class="container mt-3">
        <h3>Дякуємо за замовлення!</h3>
        <p>Ваше замовлення успішно оформлено. Наш менеджер зв'яжеться з вами найближчим часом.</p>
        <p class="text-muted">Номер вашого замовлення: {{ order.id }}</p>
        <p class="text-muted">Сума замовлення: {{ order.total_price }}</p>
        <a href="{% url 'members:profile' user.username %}" class="btn btn-primary">Перейти в особистий кабінет</a>
    </div>

{% endblock %}