apps/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),


    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/edit/', views.edit_post, name='edit_post'), 
]

apps/catalog/urls.py
from django.urls import path

from .views import CataloglistView, ProductByCategoryView, ProductDetailView

app_name = 'catalog'

urlpatterns = [
    path('', CataloglistView.as_view(), name='index'),
    path('<slug:slug>/', ProductByCategoryView.as_view() , name='category'),
    path('<slug:category_slug>/<slug:slug>/', ProductDetailView.as_view(), name='product'),
]

apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us', views.about_us, name='about_us'),
    path('contacts', views.contacts, name='contacts'),
    
]

apps/order/urls.py
from django.urls import path

from .views import (AddToCartView, CartView, DeleteFromCartView, 
                    ClearCartView, CartOrderingView, OrderComplete, CartUpdateView)

app_name = 'order'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/', AddToCartView.as_view(), name='add_to_cart'),
    
    path('cart/remove/<int:pk>/', DeleteFromCartView.as_view(), name='cart_remove'),
    path('cart/clear/', ClearCartView.as_view(), name='cart_clear'),

    path('cart/update/<int:cart_id>/<str:action>/', CartUpdateView.as_view(), name='cart_item_update'), 

    path('cart/ordering', CartOrderingView.as_view(), name='cart_ordering'),

    path("complete/<int:order_id>/", OrderComplete.as_view(), name='complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    path('blog/', include('apps.blog.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('order/', include('apps.order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include_block/_breadcrumbs.html
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'main:index' %}"><i class="fas fa-home me-1"></i>Home</a>
      </li>

      {% for url, name in breadcrumbs.items %}

      {% if url == 'current' %}
        <li class="breadcrumb-item">
            <a>{{name}}</a>
        </li>
      {% else %}
      <li class="breadcrumb-item active">
        <a href="{{url}}">{{name}}</a>
         </li>
      {% endif %}

    {% endfor %}
    </ol>
  </nav>

templates/include_block/_main_navbar.html
<a class="btn btn-outline-primary btn-sm" href="{% url 'admin:index' %}">Admin</a>

<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top" >
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:index' %}">Майстрерня карамелі</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:about_us' %}">Про нас</a>
          </li>
        
        
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:contacts' %}">Контакти</a>
          </li>
        
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'catalog:index' %}">Категорії</a>
          </li>


        </ul>
        <form class="d-flex" role="search" method="get" action="{% url 'blog:index' %}">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
          <button class="btn btn-success" type="submit">Search</button>
        </form>
        <div class="d-flex gap-2 ms-3">
          {% if user.is_authenticated %}
          <!-- Карзина -->
          <a class="btn btn-outline-primary btn-sm" href="{% url 'order:cart' %}"><i class="fa-solid fa-shopping-cart"></i>Корзина</a>





          <div class="dropdown text-end">
            <a href="" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{user.profile.get_avatar}}" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small" style="">
              <li><a class="dropdown-item" href="{% url 'members:profile' user.username %}"><i class="fa-solid fa-user"></i>Профіль</a></li>
              <li><a class="dropdown-item" href="{% url 'members:search_profile' %}"><i class="fa-solid fa-user-magnifying-glass"></i>Пошук користувачів</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'members:logout' %}"><i class="fa-solid fa-right-from-bracket"></i>Sign out</a></li>
            </ul>
          </div>
            {% else %}
            <a class="btn btn-outline-primary btn-sm" href="{% url 'members:login' %}"><i class="fa-solid fa-right-to-bracket"></i>Увійти</a>
            <a class="btn btn-outline-warning btn-sm" href="{% url 'members:signup' %}"><i class="fa-solid fa-user-plus"></i>Зареєструватися</a>
          {% endif %}
      </div>
    </div>
  </nav>











  