apps/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),


    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/edit/', views.edit_post, name='edit_post'), 
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    path('blog/', include('apps.blog.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('order/', include('apps.order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from ckeditor.fields import RichTextField


def generate_filename(instance, filename):
    # Отримати розширення файлу
    ext = filename.split('.')[-1]
    # Генерувати унікальний ідентифікатор
    filename = f'{uuid.uuid4()}.{ext}'
    return f'post_images/{filename}'


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='posts', null=True, default=None)
    
    title = models.CharField(verbose_name='Заголовок', max_length=255)
    content = RichTextField(verbose_name='Контент')
    image = models.ImageField(verbose_name='Малюнок', upload_to='generate_filename')
    thumbnail = ImageSpecField(source='image',
                                      processors=[ResizeToFill(820, 440)],
                                      format='JPEG',
                                      options={'quality': 60})

    is_published = models.BooleanField(verbose_name='Опубліковано', default=False, blank=True)
    likes = models.ManyToManyField(User, related_name='post_likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='post_dislikes', blank=True)
    views = models.IntegerField(verbose_name='Перегляди', default=0, blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)
    
    def __str__(self):
        return f'{self.title} - {self.created_at} - {self.is_published}'
    
    class Meta: # Це потрібно для відображення моделі в адмінці
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        ordering = ['-created_at']



    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            return 'https://via.placeholder.com/240x240.jpg'

    # def make_thumbnail(self, image, size=(820, 440)):
    #     img = Image.open(image)
    #     img.convert('RGBA')
    #     img.thumbnail(size)
    #     img = img.resize(size, Image.LANCZOS)

    #     thumb_io = BytesIO()
    #     img.save(thumb_io, 'PNG', quality=85)
    #     name = image.name.replace('post_images/', 'thumbnails/')
    #     thumbnail = File(thumb_io, name=name)

    #     return thumbnail



            
          
            
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост', related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='comments', null=True, default=None)
    content = models.TextField(verbose_name='Контент')
    likes = models.ManyToManyField(User, related_name='comment_likes', blank=True)
    created_at = models.DateTimeField(verbose_name='Дата створення', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата оновлення', auto_now=True)
    
    def __str__(self):
        return f'{self.author} - {self.created_at}'
    
    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ['created_at']

apps/blog/forms.py
import uuid

from django import forms
from captcha.fields import CaptchaField

from .models import Post, Comment



class PostForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Post
        fields = ['title', 'content','is_published', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control', 'id': 'imageInput', 'accept': 'image/*'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }
        
        


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }   
        

apps/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
#Paginator
from django.core.paginator import Paginator
#Search Q
from django.db.models import Q
# send email
from django.core.mail import send_mail

# Create your views here.
# @login_required
def index(request):
    query = request.GET.get('q')
    if query:
        posts = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query), is_published=True)
    else:
        posts = Post.objects.filter(is_published=True)
    create_form = PostForm()
    
    paginator = Paginator(posts, 3)
    
    context = {
        'posts': paginator.get_page(request.GET.get('page')),
        'create_form': create_form,
    }
    
    return render(request, 'blog/index.html', context)


@login_required
def post(request, post_id):
    # post = Post.objects.get(id=post_id)
    form_comment = CommentForm()
    post = get_object_or_404(Post, id=post_id)
    post.views += 1
    post.save()
    context = {
        'post': post,
        'comment_form': form_comment,
    }
    
    return render(request, 'blog/post.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        print(request.POST)
        print(request.FILES)
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            
            messages.success(request, 'Пост створено')
    return redirect('blog:index')

@login_required
def comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            print(comment)
            comment.post = post
            comment.author = request.user
            comment.save()
            messages.success(request, 'Коментар додано')
    return redirect('blog:post', post_id=post_id)

@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.likes.all():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    post.save()
    return JsonResponse({'likes': post.likes.count()})



@login_required
def dislike(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user in post.dislikes.all():
        post.dislikes.remove(request.user)
    else:
        post.dislikes.add(request.user)
    post.save()
    return JsonResponse({'dislikes': post.dislikes.count()})

@login_required
def like_comment(request, post_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, post__id=post_id)
    if request.user in comment.likes.all():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)
    comment.save()
    return JsonResponse({'likes': comment.likes.count()})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    post.delete()
    messages.success(request, 'Пост видалено')
    return redirect('members:profile', username=request.user.username)

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Пост відредаговано')
            return redirect('blog:post', post_id=post_id)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/edit_post.html', {'form': form, 'post': post})

apps/blog/templates/blog/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}



{% block content %}
    
        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn btn-primary">Зберегти</button>
            </form>
        </div>
       

{% endblock %}

apps/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}Blog{% endblock %}



{% block content %}
    

        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <h3>Блог</h3>
            <!-- Button trigger modal -->
            {% if user.is_authenticated %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
               Створити пост
            </button>
            {% endif %}
            <hr class="my-4">
            {% include 'blog/_include_blocks/_posts_show.html' with posts=posts edit=False %}

            <nav aria-label="Page navigation example" class="mt-4 align-items-center d-flex justify-content-center">
              <ul class="pagination">
                  {% if posts.has_previous %}
                      <li class="page-item">
                          <a class="page-link" href="?page=1" aria-label="First">
                              <span aria-hidden="true">&laquo;</span>
                              <span class="sr-only">1</span>
                          </a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                              <span aria-hidden="true">{{ posts.previous_page_number }}</span>
                              <span class="sr-only">{{ posts.previous_page_number }}</span>
                          </a>
                      </li>

                  {% endif %}
                  
                  
                  <li class="page-item active" aria-current="page">
                    <a class="page-link">{{ posts.number}}</a>
                  </li>
                 
                  
                  {% if posts.has_next %}
                      <li class="page-item">
                          <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                              <span aria-hidden="true">{{ posts.next_page_number }}</span>
                              <span class="sr-only">{{ posts.next_page_number }}</span>
                          </a>
                      </li>
                      <li class="page-item">
                          <a class="page-link" href="?page={{ posts.paginator.num_pages }}" aria-label="Last">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">Last</span>
                          </a>
                      </li>
                  {% endif %}
              </ul>
          </nav>
        </div>


<!-- Modal -->
<div class="modal modal-xl fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Створити пост</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <!-- <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data" id="create_form"> -->

            

            <div class="modal-body">
              <form id="postForm" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ create_form.as_p }}
                <img id="cropperImage" src="#" alt="Обрізане зображення" style="max-height: 200px">
                <button type="submit" class="btn btn-primary">Відправити</button>
            </form>
                <!-- {% csrf_token %}
                {{ create_form }} -->
            </div>
            <!-- <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="btn_create">Створити</button>
                
            </div> -->
        </form>
      </div>
    </div>
  </div>

  <script>
    
    function like(post_id){
        fetch('{% url "blog:like" 0 %}'.replace('0', post_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_' + post_id).innerText = `👍 ${data.likes}`;
        })
    }

    {% for post in posts %}
        document.getElementById('btn_like_{{post.id}}').addEventListener('click', function(){
            like({{post.id}});
        });
    {% endfor %}

    function dislike(post_id){
        fetch('{% url "blog:dislike" 0 %}'.replace('0', post_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_dislike_' + post_id).innerText = `👎 ${data.dislikes}`;
        })
    }

    {% for post in posts %}
        document.getElementById('btn_dislike_{{post.id}}').addEventListener('click', function(){
            dislike({{post.id}});
        });
    {% endfor %}
  
  {% if user.is_authenticated %}
    var cropper;
    document.getElementById('imageInput').addEventListener('change', function(event) {
      var input = event.target;
      var reader = new FileReader();
  
      reader.onload = function() {
          var image = document.getElementById('cropperImage');
          image.src = reader.result;
          
          // Після того як зображення завантажиться, створіть екземпляр Cropper
          image.onload = function() {
              cropper = new Cropper(image, {
                  aspectRatio: 16 / 9,
                  viewMode: 1,
                cropBoxMovable: true,
                cropBoxResizable: true,
                // Встановлюємо інші опції в false
                movable: false,
                zoomable: false,
                rotatable: false,
                scalable: false,
                autoCrop: true,
                  crop: function(event) {
                      // Поточна область обрізки доступна в event.detail
                      
                  }
              });
          };
      };
  
      // Зчитування вибраного файлу як URL-адреси даних
      reader.readAsDataURL(input.files[0]);
  });
  
      var form = document.getElementById('postForm');
      form.addEventListener('submit', function(event) {
          event.preventDefault();
          this.querySelector('button').disabled = true;
          cropper.getCroppedCanvas().toBlob(function(blob) {
              var formData = new FormData(form);
              formData.append('image', blob, 'cropped_image.jpg');
              
              fetch('{% url "blog:create" %}', {
                  method: 'POST',
                  body: formData,
                  headers: {
                      'X-CSRFToken': '{{ csrf_token }}'
                  }
              }).then(response => {
                  // перезавантажити сторінку після успішної відправки форми
                  if (response.ok) {
                      location.reload();
                  }
              }).catch(error => {
                  console.error('Помилка під час відправлення форми:', error);
              });
          }, 'image/jpeg');
      });

{% endif %}
</script>
  

{% endblock %}

apps/blog/templates/blog/post.html
{% extends 'base.html' %}
{% block title %}Blog{% endblock %}
{% block content %}


        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <img src="{{post.image.url}}" class="img-fluid rounded-3" width="100%" alt="...">
            <h3>{{post.title}}</h3>
            {% if user.is_authenticated and user == post.author %}
            <a href="{% url 'blog:edit_post' post.id %}" class="btn btn-sm btn-outline-primary">Редагувати</a>
            <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-sm btn-outline-danger">Видалити</a>
            {% endif %}
            <small class="text-muted">{{post.created_at}}</small>
            <small class="text-muted">{{post.author}}</small>
            <small class="text-muted">{{post.category}}</small>
            <div class="d-flex justify-content-between text-center">
                <h5><span class="badge ">👁️ {{post.views}}</span></h5>
                <h5><span class="badge ">🗨️ {{post.comments.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_like">👍 {{post.likes.count}}</span></h5>
                <h5><span class="btn btn-secondary" id="btn_dislike">👎 {{post.dislikes.count}}</span></h5>
                
            </div>
            <hr class="my-4">
            <p>{{post.content|safe}}</p>
        </div>
        <div class="mt-3 rounded-3 bg-body-tertiary p-4">
            <h5>Коментарі</h5>
            🗨️ {{post.comments.count}}
            <hr class="mx-2">
            <form action="{% url 'blog:comment' post.id %}" method="post">
                {% csrf_token %}
                
                <div class="mb-3">
                    <label for="comment" class="form-label">Ваш коментар</label>
                    <textarea class="form-control" id="comment" name="content" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Відправити</button>
            </form>
            <hr class="my-4">
            {%for comment in post.comments.all%}
                <div class="d-flex justify-content-between">
                    
                    <div>
                        <button type="button" class="btn btn-secondary" onclick="like_comment({{comment.id}})" id="btn_like_comment_{{comment.id}}">❤️ {{comment.likes.count}}</button>

                        <h5>{{comment.author}}</h5>
                        <p>{{comment.content}}</p>
                    </div>
                    <div>
                        <small class="text-muted text-end">{{comment.created_at}}</small>
                    </div>
                </div>
                <hr>
            
            {%endfor%}
        </div>


<script>
     document.getElementById('btn_like').addEventListener('click', function(){
        fetch('{% url "blog:like" post.id %}')
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like').innerText = `👍 ${data.likes}`;
        })
        .catch(error => console.log(error));
    });

    function like_comment(comment_id){
        fetch('{% url "blog:like_comment" post.id 0 %}'.replace('0', comment_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_like_comment_' + comment_id).innerText = `❤️ ${data.likes}`;
        })
        .catch(error => console.log(error));
    }

</script>

<script>
    document.getElementById('btn_dislike').addEventListener('click', function(){
        fetch('{% url "blog:dislike" post.id %}')
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_dislike').innerText = `👎 ${data.dislikes}`;
        })
        .catch(error => console.log(error));
    });
</script>
{% endblock %}