apps/blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),


    path('<int:post_id>/', views.post, name='post'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/comment/', views.comment, name='comment'),
    path('<int:post_id>/like/', views.like, name='like'),
    path('<int:post_id>/dislike/', views.dislike, name='dislike'),
    path('<int:post_id>/comment/<int:comment_id>/like/', views.like_comment, name='like_comment'),
    
    path('<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('<int:post_id>/edit/', views.edit_post, name='edit_post'), 
]

apps/members/urls.py
from django.urls import path
from .views import *

app_name = 'members'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
    
    path('profile/update/', profile_update_view, name='profile_update'),
    path('password/change/', password_change_view, name='change_password'),
    
    path('profile/<str:username>', profile_view, name='profile'),
    path('profile/<str:username>/follow/', follow_view, name='follow'),
    path('profile/<str:username>/privacy/', privacy_view, name='privacy'),
    
    path('search/', search_view, name='search_profile'),
    
    ] 

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('members/', include('apps.members.urls')),
    path('blog/', include('apps.blog.urls')),
    path('catalog/', include('apps.catalog.urls')),
    path('order/', include('apps.order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/members/models.py
from django.db import models
from django.contrib.auth.models import User

from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

from ckeditor.fields import RichTextField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(verbose_name='Аватар', upload_to='avatars/', default='avatars/default.png')
    avatar_thumbnail = ImageSpecField(source='avatar',
                                      processors=[ResizeToFill(300, 300)],
                                      format='JPEG',
                                      options={'quality': 60})
    bio = RichTextField(verbose_name='Біографія', max_length=200, blank=True)
    birth_date = models.DateField(verbose_name='Дата народження', null=True, blank=True)
    location = models.CharField(verbose_name='Місце проживання', max_length=255, blank=True)
    website = models.URLField(verbose_name='Веб-сайт', blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=15, blank=True)
    is_private = models.BooleanField(verbose_name='Приватний профіль', default=False)
    
    followers = models.ManyToManyField(User, related_name='following', blank=True)
    
    
    def follow(self, user):
        self.followers.add(user)
    
    def unfollow(self, user):
        self.followers.remove(user)
        
    def is_following(self, user):# 
        return user in self.followers.all()
    
    def get_followers(self):
        return self.followers.all()
    #fIX ME 
    # #Ця функція повертає всіх користувачів, які підписані на даного користувача
    def get_following(self):
        print(Profile.objects.filter(followers=self.user))
        return Profile.objects.filter(followers__in=[self.user])
    
    
    def get_avatar(self):
        if self.avatar:
            return self.avatar_thumbnail.url
        return '/media/avatars/default.png'
    
    def __str__(self):
        return f'{self.user.username}'

apps/order/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Кількість')
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity} шт.'
    
    class Meta:
        verbose_name = 'Кошик'
        verbose_name_plural = 'Кошики'
        ordering = ('id',)
        # unique_together = ('user', 'product' ) # Щоб не можна було додати один і той же товар в корзину більше одного разу
    
    def total_price(self):
        return self.product.price * self.quantity
        
#ДОробити модель обраного товару та відображення обраного товару в адмінці
class Favorite(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    
    def __str__(self):
        return f'{self.product.name}'
    
    class Meta:
        verbose_name = 'Обране'
        verbose_name_plural = 'Обране'
        unique_together = ('user', 'product' ) # Щоб не можна було додати один і той же товар в обране більше одного разу
        
        
class Order(models.Model):
    STATUS_CHOICES = (
        ('in_progress', 'В обробці'),
        ('sent', 'Відправлено'),
        ('completed', 'Завершено'),
        ('canceled', 'Скасовано')
    )
    STATUS_PAID = (
        (True, 'Оплачено'),
        (False, 'Не оплачено')
    )
    
    
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, verbose_name='Користувач')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Загальна вартість')
    
    first_name = models.CharField(max_length=255, verbose_name='Ім\'я')
    last_name = models.CharField(max_length=255, verbose_name='Прізвище')
    email = models.EmailField(verbose_name='Email', blank=True, null=True)
    phone = PhoneNumberField(verbose_name='Телефон')
    address = models.CharField(max_length=255, verbose_name='Адреса')
    comment = models.TextField(verbose_name='Коментар', blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')

    paid = models.BooleanField(verbose_name='Оплачено', choices=STATUS_PAID, default=False)
    status = models.CharField(max_length=255, verbose_name='Статус', choices=STATUS_CHOICES, default='in_progress')

    class Meta:
        verbose_name = 'Замовлення'
        verbose_name_plural = 'Замовлення'
        ordering = ('-created_at',)
        
    def __str__(self):
        return f'Замовлення №{self.id}'
    
    
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Замовлення')
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveIntegerField(verbose_name='Кількість')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity} шт.'
    
    class Meta:
        verbose_name = 'Товар замовлення'
        verbose_name_plural = 'Товари замовлення'
        
    def total_price(self):
        return self.product.price * self.quantity

apps/members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User

from .models import Profile

from captcha.fields import CaptchaField

class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, )
    last_name = forms.CharField(max_length=30, required=False, )
    email = forms.EmailField(max_length=254, help_text='ЛОл напиши свій email', required=True, label='Email')
    captcha = CaptchaField()
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'captcha')
        # widgets = {
        #     'username': forms.TextInput(attrs={'class': 'form-control'}),
        #     'first_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        #     'email': forms.EmailInput(attrs={'class': 'form-control'}),
        #     'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        #     'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        # }

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio', 'birth_date', 'location', 'website', 'phone']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'class': 'form-control'}),
            'birth_date': forms.DateInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'website': forms.URLInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        field_classes = {"username": UsernameField}
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

apps/members/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import UserCreateForm, ProfileUpdateForm , UserUpdateForm
from apps.blog.forms import PostForm
from .models import Profile

from apps.order.models import Order


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Ви увійшли як {username}')
                return redirect('members:profile', username=username)
        # else:
        #     messages.add_message(request, messages.ERROR, 'Неправильний логін або пароль', extra_tags='danger')
    else:
        form = AuthenticationForm()
    return render(request, 'members/login.html', {'form': form})
@login_required
def logout_view(request):
    logout(request)
    messages.info(request, 'Ви вийшли з системи')
    return redirect('members:login')
def signup_view(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.email = form.cleaned_data.get('email')
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            messages.success(request, f'Ви успішно зареєструвалися як {user.username}')
            return redirect('members:profile', username=user.username)
    else:
        form = UserCreateForm()
    return render(request, 'members/signup.html', {'form': form})
@login_required
def profile_view(request, username=None):
    if username is None:
        username = request.user
    
    
    if request.user.username == username:
        form_create_post = PostForm()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        orders = Order.objects.filter(user=request.user).prefetch_related('orderproduct_set').prefetch_related('orderproduct_set__product').prefetch_related('orderproduct_set__product__images').order_by('created_at')
        context = {
            'form_create_post': form_create_post,
            'user_form': user_form,
            'profile_form': profile_form,
            'user_profile': request.user,
            'profile': request.user.profile,
            'another_user': False,
            'orders': orders,
        }
    else:
        user = get_object_or_404(User, username=username)
        profile = get_object_or_404(Profile, user=user)
        context = {
            'another_user': True,
            'user_profile': user,
            'profile': profile,
            'is_following': request.user.profile.is_following(user),
        }
    return render(request, 'members/profile.html', context)

@login_required
def profile_update_view(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Ваш профіль успішно оновлено')
        else:
            messages.error(request, 'Вибачте, щось пішло не так')
    return redirect('members:profile', username=request.user.username)
    
    
    
#Search People
def search_view(request):
    if request.method == 'GET':
        query = request.GET.get('q')
        if query:
            users = User.objects.filter(username__icontains=query)
            return render(request, 'members/search.html', {'users': users})
    return render(request, 'members/search.html', {'users': None})


@login_required
def follow_view(request, username):
    user = get_object_or_404(User, username=username)
    if request.user != user:
        profile = request.user.profile
        if profile.is_following(user):
            profile.unfollow(user)
            messages.info(request, f'Ви відписались від {user.username}')
        else:
            profile.follow(user)
            messages.success(request, f'Ви підписались на {user.username}')
    return redirect('members:profile', username=username)

@login_required
def privacy_view(request, username):
    user = get_object_or_404(User, username=username)
    if request.user == user:
        profile = user.profile
        profile.is_private = not profile.is_private
        profile.save()
        messages.success(request, 'Ваші налаштування приватності успішно змінені')
    return redirect('members:profile', username=username)





@login_required
def password_change_view(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Ваш пароль успішно змінено')
            return redirect('members:profile', username=request.user.username)
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'members/change_password.html', {'form': form})

apps/members/templates/members/change_password.html
{% extends 'base.html' %}

{% block title %}Профіль{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
    <div class="row g-4">
        <div class="col-12 col-md-4">
          <img src="{{user.profile.get_avatar}}" class="img-fluid rounded-circle mx-auto d-block" alt="...">
        </div>
      
        <div class="col-8">
          <h3>Зміна пароля</h3>
          <form method="post">
            {% csrf_token %}
            <!-- {{ form.as_p }} -->
            {{ form | crispy }}
            <button type="submit" class="btn btn-primary">Змінити пароль</button>
          </form>

          
        </div>
    </div>
</div>
{% endblock %}

apps/members/templates/members/login.html
{% extends 'base.html' %}
{% block title %}ЛОГІН{% endblock %}
{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Логін</h3>
        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="username" class="form-label">Ім'я користувача</label>
                <input type="text" class="form-control" id="username" name="username" value="{{ form.username.value|default_if_none:'' }}" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Пароль</label>
                <input type="password" class="form-control" id="password" name="password" value="{{ form.password.value|default_if_none:'' }}" required>
            </div>
            <button type="submit" class="btn btn-primary">Увійти</button>
            <span class="ms-2">або <a href="{% url 'members:signup' %}">зареєструватися</a></span>
        </form>
</div>
{% endblock %}

apps/members/templates/members/profile.html
{% extends 'base.html' %}
{% block title %}Профіль{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
    <div class="row g-4">
        <div class="col-12 col-md-4">
          <img src="{{profile.get_avatar}}" class="img-fluid rounded-circle mx-auto d-block" alt="...">
          {% if another_user %}         
          <div class="d-flex justify-content-center mt-2">
            {% if not is_following %}
            <a href="{% url 'members:follow' user_profile.username %}" class="btn btn-primary">Підписатися</a>
            {% else %}
            <a href="{% url 'members:follow' user_profile.username %}" class="btn btn-danger">Відписатися</a>
            {% endif %}
          </div>
          {% endif %}
        </div>
        
      {% if not profile.is_private or not another_user  %}
        <div class="col-8">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item" role="presentation">
              <a class="nav-link active" id="simple-tab-0" data-bs-toggle="tab" href="#simple-tabpanel-0" role="tab" aria-controls="simple-tabpanel-0" aria-selected="true">Info</a>
            </li>
            {% if not another_user %}
            <li class="nav-item" role="presentation">
              <a class="nav-link" id="simple-tab-2" data-bs-toggle="tab" href="#simple-tabpanel-2" role="tab" aria-controls="simple-tabpanel-2" aria-selected="false">Orders</a>
            </li>
            <li class="nav-item" role="presentation">
              <a class="nav-link" id="simple-tab-1" data-bs-toggle="tab" href="#simple-tabpanel-1" role="tab" aria-controls="simple-tabpanel-1" aria-selected="false">Settings</a>
            </li>

            {% endif %}
          </ul>
          <div class="tab-content pt-5" id="tab-content">
            <div class="tab-pane active" id="simple-tabpanel-0" role="tabpanel" aria-labelledby="simple-tab-0">
              <p>Ім'я користувача: {{ user_profile.username }}</p>
              <p>Ім'я: {{ user_profile.first_name }}</p>
              <p>Прізвище: {{ user_profile.last_name }}</p>
              <p>Електронна пошта: {{ user_profile.email }}</p>
              <p>Дата реєстрації: {{ user_profile.date_joined }}</p>
              <p>Дата останнього входу: {{ user_profile.last_login }}</p>
              <p>Біо: {{ profile.bio|safe }}</p>
              <p>Дата народження: {{ profile.birth_date }}</p>
              <p>Місце проживання: {{ profile.location }}</p>

            </div>
            {% if not another_user %}   
            <div class="tab-pane" id="simple-tabpanel-2" role="tabpanel" aria-labelledby="simple-tab-2">
              <h5>Замовлення</h5>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">№</th>
                    <th scope="col">Дата</th>
                    <th scope="col">Остання зміна</th>
                    <th scope="col">Сума</th>
                    <th scope="col">Статус</th>
                  </tr>
                </thead>
                <tbody>
                  {% for order in orders.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order.created_at }}</td>
                    <td>{{ order.updated_at }}</td>
                    <td>{{ order.total_price }}</td>
                    <td>{{ order.get_status_display }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>

          </div>    
            <div class="tab-pane" id="simple-tabpanel-1" role="tabpanel" aria-labelledby="simple-tab-1">
                <h5>Редагування профілю</h5>
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editProfileModal">
                  Змінити профіль
                </button>
                <hr class="my-4">
                <h5>Приватність</h5>
                <form action="{% url 'members:privacy' user_profile.username %}" method="post">
                  {% csrf_token %}
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" name="is_private" {% if profile.is_private %} checked {% endif %}>
                    <label class="form-check-label" for="flexCheckDefault">
                      Приватний профіль
                    </label>
                  </div>
                  <button type="submit" class="btn btn-primary mt-4">Зберегти</button>
                </form>
                <hr class="my-4">
                <h5>Змінити пароль</h5>
                <a href="{% url 'members:change_password' %}" class="btn btn-primary">Змінити пароль</a>
                <hr class="my-4">              

            </div>
            {% endif %}
          </div>
        </div>
        {% if profile.get_followers %}
        <div class="col-12">
          <hr class="my-4">
          <h3 class="text-center">Підписки</h3>
          <div class="row g-4">
            <ul class="list-unstyled">
              {% for follower in profile.get_followers %}
              <li><div class="d-flex align-items-left">
                <img src="{{follower.profile.get_avatar}}" class="rounded-circle" alt="..." style="width: 30px; height: 30px;">
                <a href="{% url 'members:profile' follower.username %}" class="text-decoration-none text-primary hover-underline">
                    <small class="ms-3">@{{ follower.username }}</small>
                </a>
            </div>
          </li>
              {% endfor %}  
            </ul>
           
          </div>
        </div>
        {% endif %}
        {% if profile.get_following %}
        <div class="col-12">
          <hr class="my-4">
          <h3 class="text-center">Підписники</h3>
          <div class="row g-4">
            <ul class="list-unstyled">
            {% for follower in profile.get_following %}
            <li><div class="d-flex align-items-left">
              <img src="{{follower.get_avatar}}" class="rounded-circle" alt="..." style="width: 30px; height: 30px;">
              <a href="{% url 'members:profile' follower.user.username %}" class="text-decoration-none text-primary hover-underline">
                  <small class="ms-3">@{{ follower.user.username }}</small>
              </a>
              </div></li>
            
            {% endfor %}  
          </ul>
          </div>
        </div>
        {% endif %}
      {% endif %}
    </div>
</div>
{% if not profile.is_private or not another_user  %}
<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Пости</h3>
        {% if not another_user %}
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                Створити пост
            </button>
        <hr class="my-4">
        {% include 'blog/_include_blocks/_posts_show.html' with posts=user_profile.posts.all edit=True %}
        {% else %}
        <hr class="my-4">
        {% include 'blog/_include_blocks/_posts_show.html' with posts=user_profile.posts.all edit=False %}
        {% endif %} 
    </div>
{% endif %}


{% if not another_user %}

      <div class="modal fade" id="editProfileModal" tabindex="-1" aria-labelledby="editProfileModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="editProfileModalLabel">Редагувати профіль</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="{% url 'members:profile_update' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form | crispy}}
                {{ profile_form | crispy }}
                <button type="submit" class="btn btn-primary mt-4">Зберегти</button>
              </form>
          </div>
        </div>
      </div>
{% endif %}



<script>
    
  function like(post_id){
      fetch('{% url "blog:like" 0 %}'.replace('0', post_id))
      .then(response => response.json())
      .then(data => {
          document.getElementById('btn_like_' + post_id).innerText = `👍 ${data.likes}`;
      })
  }

  {% for post in user_profile.posts.all %}
      document.getElementById('btn_like_{{post.id}}').addEventListener('click', function(){
          like({{post.id}});
      });
  {% endfor %}

  function dislike(post_id){
        fetch('{% url "blog:dislike" 0 %}'.replace('0', post_id))
        .then(response => response.json())
        .then(data => {
            document.getElementById('btn_dislike_' + post_id).innerText = `👎 ${data.dislikes}`;
        })
    }

    {% for post in user_profile.posts.all %}
        document.getElementById('btn_dislike_{{post.id}}').addEventListener('click', function(){
            dislike({{post.id}});
        });
    {% endfor %}

</script>


{% endblock %}

apps/members/templates/members/search.html
{% extends 'base.html' %}

{% block title %}Пошук користувачів{% endblock %}



{% block content %}

<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Пошук користувачів</h3>
        <form method="get">
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="q">
            </div>
            <button type="submit" class="btn btn-primary">Знайти</button>
        </form>
</div>

{% if users %}
<div class="mt-4 rounded-3 bg-body-tertiary p-4">
    <h3 class="text-center">Результати пошуку</h3>
    <hr class="my-4">
    <div class="row g-4">
        {% for user in users %}
        <div class="col-12 col-md-4">
            <div class="card">
                <img src="{{user.profile.get_avatar}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ user.username }}</h5>
                    <p class="card-text">{{ user.profile.bio }}</p>
                    <a href="{% url 'members:profile' user.username %}" class="btn btn-primary">Переглянути профіль</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% endblock %}

apps/members/templates/members/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block title %}Зареєструватися{% endblock %}


{% block content %}
<div class="mt-4 rounded-3 bg-body-tertiary p-4">
        <h3 class="text-center">Зареєструватися</h3>
        <form method="post">
            {% csrf_token %}    
            {{form | crispy}}
            <button type="submit" class="btn btn-primary">Зареєструватися</button>
            <span class="ms-2">або <a href="{% url 'members:login' %}">увійти</a></span>
        </form>
{% endblock %}